FROM node:alpine
WORKDIR /app

RUN apk add --no-cache openssl

ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    rm dockerize-alpine-linux-amd64-$DOCKERIZE_VERSION.tar.gz

RUN apk add --no-cache bash

RUN npm init -y
COPY package.json /app/package.json
    
RUN npm install express sequelize mysql2 sequelize-cli && \
    npm install --save-dev nodemon

EXPOSE 3000

ENTRYPOINT [ "dockerize", "-wait", "tcp://mysql:33060", "-timeout", "30s" ]
CMD ["npm", "start"]
